@extends('master/container')
<meta name="description" content="{{ $meta_description }}">
<meta name="keywords" content="{{ $meta_keywords }}">
<meta name="author" content="{{ $meta_author }}">
<meta property="og:title" content="{{ ucfirst($meta_description) }} - {{ $sitename }}"/>
@stop
@section('content')
<div id="content">
    <!--======= Details Features Tabs =========-->
    <section id="det_fea" class="fea_colour">
      <div class="features_bg">
        <div class="container">
          <ul class="row features">
            <li class="col-md-4 bg_color_1 nopadding">
              <div class="icon wow bounceInUp" data-wow-duration="0.90s" data-wow-delay="200ms"> <i class="ion-clipboard bg_color_1"></i> </div>
              <h4>Mission statement</h4>
              <p>To educate and guide both current and upcoming generations to a successful and prosperous financial future.</p>
            </li>
            <li class="col-md-4 bg_color_2 nopadding">
              <div class="icon wow bounceInUp"  data-wow-duration="0.90s" data-wow-delay="400ms"> <i class="ion-ios7-clock-outline bg_color_2"></i> </div>
              <h4>Vision statement</h4>
              <p>Within five years, the current generation will gain knowledge and understanding on how to save and plan for a better future. The upcoming generations will learn how to save and manage money through the implementation of UFG in the school system. This will better the economy by substantially reducing debt that is generated by the current “American way” of living.</p>
            </li>
            <li class="col-md-4 bg_color_3 nopadding">
              <div class="icon wow bounceInUp" data-wow-duration="0.90s" data-wow-delay="600ms"> <i class="ion-ios7-videocam bg_color_3"></i> </div>
              <h4>PROCESS PLAN</h4>
              <p>Tree Simple Steps</p>
              <p>Educate - Guidance - Planning</p>
            </li>
          </ul>
        </div>
      </div>
      
      <!--======= ICONS =========-->
      <div class="learngo bg_color_2">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h4 class="border">UF<span>Guidance</span></h4>
              <p>It is a long established fact that a reader will be distracted by the readable content.</p>
              
              <!--======= ICONS =========-->
              <div class="features_services">
                <ul class="row">
                  
                  <!--======= ICONS =========-->
                  <li class="col-md-6">
                    <div class="icon  wow bounceIn"  data-wow-delay="200ms" data-wow-iteration="2"> <i class="ion-help-buoy bg_color_3"></i> </div>
                    <h4>What is UFG</h4>
                    <p>An organization of young adults who have set out to educate and guide the youth to a successful, prosperous financial future. UFG works with a purpose to help the current youth and upcoming generations. </p>
                  </li>
                  
                  <!--======= ICONS =========-->
                  <li class="col-md-6">
                    <div class="icon  wow bounceInbounceIn"  data-wow-delay="400ms" data-wow-iteration="2"> <i class="ion-ios7-people bg_color_3"></i> </div>
                    <h4>Who is UFG</h4>
                    <p>UFG was started by a young man in San Bernardino who witnessed a lot of his college peers wasting the money that they received from FAFSA and/or their parents. He noticed that they were spending this loaned money on Vegas trips, parties, clothes, and other things that were irrelevant to their future. Those poor financial habits continued as they advanced in their lives and careers. Now UFG is built and managed by young adults who know what it’s like in today’s world, being influenced by so many social and political factors. UFG members are college students, high school students, young parents, young men and women who have held mediocre jobs while they dreamt of long term careers. UFG is youth teaching youth, working together to rise up against the new slavery: Debt. </p>
                  </li>
                  
                  <!--======= ICONS =========-->
                  <li class="col-md-6">
                    <div class="icon  wow bounceIn" data-wow-delay="600ms" data-wow-iteration="2"> <i class="ion-hammer bg_color_3"></i> </div>
                    <h4>Why UFG</h4>
                    <p>UFG aims to fill in the missing piece of the educational framework that currently molds our youth. Where math class teaches you how to count money, UFG teaches how to use it as a tool in life. Where economics teaches you how money flows through society, UFG teaches you how manage your own cash flow without getting in debt. Where school teaches you how you can make money for the rest of your life, UFG teaches how to work with the money you make to build a successful future and be a positive influence to those around you.</p>
                  </li>
                  
                  <!--======= ICONS =========-->
                  <li class="col-md-6">
                    <div class="icon  wow bounceIn" data-wow-delay="800ms" data-wow-iteration="2s"> <i class="ion-filing bg_color_3"></i> </div>
                    <h4>How does UFG work</h4>
                    <p>UFG is prevention, not intervention. Our goal is to avoid debt and build a lasting future; to develop good financial habits before bad ones are instilled and harder to break. UFG works by raising young people to be prepared men and women of a successful financial future. UFG hosts seminars, providing this education, in high schools and in colleges.</p>
                  </li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>

    <div id="phone_number">
      <div class="container">
          <div id="disqus_thread"></div>
          <script type="text/javascript">
              /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
              var disqus_shortname = 'ufguidance'; // required: replace example with your forum shortname

              /* * * DON'T EDIT BELOW THIS LINE * * */
              (function() {
                  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
              })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
          <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
      </div>
    </div>
    @include('master/footer')
  </div>
@stop
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'ufguidance'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());

    window.doorbellOptions = {
        appKey: 'QkAFkToVyHoV8FWzTbbfYUZx9eaOCjCUhPxG3dL7ZtoS0Fu4TnDmhxs23lxqo2h4'
    };
    (function(d, t) {
        var g = d.createElement(t);g.id = 'doorbellScript';g.type = 'text/javascript';g.async = true;g.src = 'https://doorbell.io/button/348';(d.getElementsByTagName('head')[0]||d.getElementsByTagName('body')[0]).appendChild(g);
    }(document, 'script'));
</script>
